starqltechn: init.qcom: Fix compilation errors
host_init_verifier: Command 'load_system_props' (device/samsung/starqltechn/rootdir/etc/init.qcom.rc:1097) failed: 'load_system_props' is deprecated

host_init_verifier: Failed to parse init scripts with 1 error(s).

Signed-off-by: PurpleVoyager401 <just.aenthusiast@gmail.com>